### PR TITLE
set ExternalTrafficPolicy of kubeapi server service to Local

### LINKED ISSUE #25: KubeAPI Server can't get accessed
**What happened**:
After set ExternalTrafficPolicy of kube-apiserver service to local, some shoot clusters can't be accessed. The node port exposed on the node where apiserver pod is running can't be connected. After investigated by TCPDump,  the *syn* tcp packets from Cloud SLB probers are not responded. It is weird. It could be iptable rules issue because some shoots are normal. Need some time to track. But as it is a very critical issue for Gardener users, let's set *ExternalTrafficPolicy* back to *cluster* for now.
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Not always. All malfunctional shoots are in Hangzhou region while seed is in Shanghai.
**Anything else we need to know?**:

**Environment**:

- Gardener version (if relevant):
- Extension version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

### PR DESCRIPTION
**Pull request by jia-jerry**
**How to categorize this PR?**

/area control-plane
/kind enhancement
/priority normal
/platform alicloud

**What this PR does / why we need it**:
Set ExternalTrafficPolicy of kube-apiserver service to Local in Alicloud. 
**Which issue(s) this PR fixes**:
Fixes #25 

**Special notes for your reviewer**:

**Release note**:

```improvement operator
Set ExternalTrafficPolicy of kube-apiserver service to Local in Alicloud.
```

### CODE REVIEW

**Comment by rfranzke** [comment]
What about the issues you mentioned in #25? Why are they resolved now?

File: pkg/webhook/controlplaneexposure/ensurer_test.go [hunk 1]
```diff
@@ -192,6 +200,25 @@ var _ = Describe("Ensurer", func() {
 			checkKubeAPIServerDeployment(dep)
 		})
 	})
+	Describe("#EnsureKubeAPIServerService", func() {
+		It("should set ExternalTrafficPolicy to Local for vpn-shoot service", func() {
```
Comment (rfranzke) [inline pkg/webhook/controlplaneexposure/ensurer_test.go:204]:
```suggestion
		It("should set ExternalTrafficPolicy to Local for kube-apiserver service", func() {
```

File: pkg/webhook/controlplaneexposure/ensurer_test.go [hunk 2]
```diff
@@ -192,6 +200,25 @@ var _ = Describe("Ensurer", func() {
...
+			ensurer := NewEnsurer(etcdStorage, logger)
+			err := ensurer.EnsureKubeAPIServerService(context.TODO(), dummyContext, svc, nil)
+			Expect(err).To(Not(HaveOccurred()))
+			Expect(svc.Spec.ExternalTrafficPolicy).To(Equal(corev1.ServiceExternalTrafficPolicyTypeLocal))
+		})
+
+		It("should not overwrite .spec.healthCheckNodePort for vpn-shoot service", func() {
```
Comment (rfranzke) [inline pkg/webhook/controlplaneexposure/ensurer_test.go:211]:
```suggestion
		It("should not overwrite .spec.healthCheckNodePort for kube-apiserver service", func() {
```

**Review by minchaow — APPROVED** [review]
/lgtm
